# Generated by Django 2.2 on 2019-04-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='phone',
        ),
        migrations.AddField(
            model_name='trip',
            name='guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='guestLimit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
